version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: weddingbackend
    ports:
      - "8000:8000"
    environment:
      - NAME=World
    command: ["uvicorn", "wedding_app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    volumes:
      - ./:/app
