version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: weddingbackend
    ports:
      - "8000:8000"
    env_file:
      - .env
    # command: ["uvicorn", "wedding_app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload", "--ssl-keyfile", "/app/keyfile.pem", "--ssl-certfile", "/app/certfile.pem"]
    volumes:
      - ./wedding_app:/app/wedding_app:ro
    depends_on:
      - db

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"

volumes:
  postgres_data:
